# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: rosa-cleaner
#   namespace: rosa-cleaner
# secrets:
#   - name: private-repo-auth
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rosa-cleaner-builder-pvc
  namespace: rosa-cleaner
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rosa-cleaner
  namespace: rosa-cleaner
spec:
  workspaces:
  - name: workspace
  params:
  - default: rosa-cleaner
    name: APP_NAME
    type: string
  - default: https://github.com/rh-mobb/managed-openshift-cleaner
    name: GIT_REPO
    type: string
  - default: main
    name: GIT_REVISION
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/rosa-cleaner/rosa-cleaner
    name: IMAGE_NAME
    type: string
  - default: ./rosa
    name: PATH_CONTEXT
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build-and-push
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: TLSVERIFY
      value: "false"
    - name: CONTEXT
      value: $(params.PATH_CONTEXT)
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: oc-apply-cronjob
    params:
    - name: SCRIPT
      value: |
        oc apply -f <(cat ./rosa/examples/cronjob/cronjob.yaml | sed 's/rosa-cleaner:latest$/rosa-cleaner@$(tasks.build-and-push.results.IMAGE_DIGEST)/')
      # sleep 1
      # oc patch cronjob rosa-cleaner --type=merge -p='{"spec": "jobTemplate": {"spec": {"template": {"spec": {"containers": [{"image": "$(tasks.build-and-push.results.IMAGE_DIGEST)"}}]}}}}'
      # value:
      #   - "apply"
      #   - "-f"
      #   - '<(cat cronjob/cronjob.yaml | sed "s/:latest$/@`cat /workspace/source/image-digest`/")'
    runAfter:
    - build-and-push
    taskRef:
      kind: ClusterTask
      name: openshift-client
    workspaces:
    - name: manifest-dir
      workspace: workspace

