apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rosa-cleaner
spec:
  destination:
    name: ''
    namespace: rosa-cleaner
    server: 'https://kubernetes.default.svc'
  source:
    path: ./rosa/examples/cronjob
    repoURL: 'https://github.com/rh-mobb/managed-openshift-cleaner'
    targetRevision: HEAD
  project: rosa-cleaner
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
