---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: rosa-cleaner
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: content-type
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          tekton.dev/pipeline: rosa-cleaner
        name: rosa-cleaner-$(uid)
      spec:
        params:
          - name: APP_NAME
            value: $(tt.params.git-repo-name)
          - name: GIT_REPO
            value: $(tt.params.git-repo-url)
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
        pipelineRef:
          name: rosa-cleaner
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: rosa-cleaner-builder-pvc
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: rosa-cleaner
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: rosa-cleaner
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: rosa-cleaner
    template:
      name: rosa-cleaner
