---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: rosa-cleaner-default
    app.kubernetes.io/component: rosa-cleaner-default
    app.kubernetes.io/instance: rosa-cleaner-default
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: rosa-cleaner-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
  name: rosa-cleaner-default
  namespace: rosa-cleaner
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/rosa-cleaner/rosa-cleaner:latest
            imagePullPolicy: Always
            name: rosa-cleaner
            command:
            - ./rosa-cleaner.py
            volumeMounts:
            - name: rosa-auth
              mountPath: /auth
              readOnly: true
            env:
            - name: EXCLUDE_REGIONS
              value: "us-east-1,us-east-2,us-west-1,us-west-2"
            - name: OCM_JSON
              value: /auth/ocm.json
            - name: DELETE
              value: "1" # change to 1 to delete the old clusters
            - name: SKIP_CLUSTERS
              value: "" # csv of clusters to skip.  mobb-infra is always skipped.
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-iam-cleaner-secret
                  key: aws_access_key_id
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-iam-cleaner-secret
                  key: aws_secret_access_key
                  optional: false
          volumes:
          - name: rosa-auth
            secret:
              secretName: openshift-cluster-manager-credentials
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: rosa-cleaner-east
    app.kubernetes.io/component: rosa-cleaner-east
    app.kubernetes.io/instance: rosa-cleaner-east
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: rosa-cleaner-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
  name: rosa-cleaner-east
  namespace: rosa-cleaner
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/rosa-cleaner/rosa-cleaner:latest
            imagePullPolicy: Always
            name: rosa-cleaner
            command:
            - ./rosa-cleaner.py
            volumeMounts:
            - name: rosa-auth
              mountPath: /auth
              readOnly: true
            env:
            - name: INCLUDE_REGIONS
              value: "us-east-1,us-east-2"
            - name: OCM_JSON
              value: /auth/ocm.json
            - name: DELETE
              value: "1" # change to 1 to delete the old clusters
            - name: SKIP_CLUSTERS
              value: "" # csv of clusters to skip.  mobb-infra is always skipped.
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-iam-cleaner-secret
                  key: aws_access_key_id
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-iam-cleaner-secret
                  key: aws_secret_access_key
                  optional: false
          volumes:
          - name: rosa-auth
            secret:
              secretName: openshift-cluster-manager-credentials
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: rosa-cleaner-west
    app.kubernetes.io/component: rosa-cleaner-west
    app.kubernetes.io/instance: rosa-cleaner-west
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: rosa-cleaner-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
  name: rosa-cleaner-west
  namespace: rosa-cleaner
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: image-registry.openshift-image-registry.svc:5000/rosa-cleaner/rosa-cleaner:latest
            imagePullPolicy: Always
            name: rosa-cleaner
            command:
            - ./rosa-cleaner.py
            volumeMounts:
            - name: rosa-auth
              mountPath: /auth
              readOnly: true
            env:
            - name: INCLUDE_REGIONS
              value: "us-west-1,us-west-2"
            - name: OCM_JSON
              value: /auth/ocm.json
            - name: DELETE
              value: "1" # change to 1 to delete the old clusters
            - name: SKIP_CLUSTERS
              value: "mhs-pri-link" # csv of clusters to skip.  mobb-infra is always skipped.
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-iam-cleaner-secret
                  key: aws_access_key_id
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-iam-cleaner-secret
                  key: aws_secret_access_key
                  optional: false
          volumes:
          - name: rosa-auth
            secret:
              secretName: openshift-cluster-manager-credentials
          restartPolicy: OnFailure
